# Generated by Django 5.2.10 on 2026-02-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_sessions_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='role',
            field=models.CharField(default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(default='user', max_length=10),
        ),
    ]
