# Generated by Django 5.2.10 on 2026-02-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_sessions_role_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='session',
            field=models.CharField(default=''),
        ),
    ]
